[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Static assets - serve directly without redirect
[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.mjs"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpeg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.gif"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.ico"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.woff"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.woff2"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.json"
  to = "/:splat"
  status = 200

# SPA fallback - redirect everything else to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[build.environment]
  VITE_SUPABASE_URL = "https://gfinjkozooknqcqvxrep.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmaW5qa296b29rbnFjcXZ4cmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjMwNTQsImV4cCI6MjA3NDQzOTA1NH0.GcWVZ0-of4RrWJ0eASUTvJH1bC95eS8dSyU0foE3hHY"