[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Asset files - serve directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# SPA fallback - catch all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/node_modules/motion-dom/**/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[build.environment]
  VITE_SUPABASE_URL = "https://gfinjkozooknqcqvxrep.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmaW5qa296b29rbnFjcXZ4cmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjMwNTQsImV4cCI6MjA3NDQzOTA1NH0.GcWVZ0-of4RrWJ0eASUTvJH1bC95eS8dSyU0foE3hHY"